
varsender = "eduresistor@gmail.com"
varsender_password = "qydk lsra eiht ehuw"

welcome_content ="Hi, welcome to Eduresistor your basic online calculator on resistors.\n It is free! your are registered we hope you will enjoy!!\n\nBest regards,\nEduresistor\n\n\nPS: This email is autogenerated do not reply."

